#!/usr/bin/env sh

# Usage: doc/api.md#confirm

confirm(){
    if [ -z "${1}" ]; then
        echo "confirm: arguments are missing"
        return 127
    else
        question="${1}"
        yes_callback="${2}"
        no_callback="${3}"

        # Ask a 'yes/no' type question
        echo "${question} [y/n]? "

        # Listen for input
        old_stty_cfg=$(stty -g)
        stty raw -echo
        response=$( while ! head -c 1 | grep -i '[ny]'; do true; done )
        stty "${old_stty_cfg}"

        # Respond to input
        if echo "$response" | grep -iq "^y"; then
            "${yes_callback}"
        elif [ -n "${2}" ]; then
            "${no_callback}"
        fi
    fi
}
