#!/usr/bin/env sh

# Usage: doc/api.md#print-text

# Create an alias
. ./shell/common/expand-aliases
alias print-text='print_text'

print_text(){
    if [ -z "${1}" ]; then
        echo "print-text: arguments are missing"
        return 127
    fi

	start=$(tput setaf "${1}")
	stop=$(tput sgr0)

	printf '%s\n' "${start}${2}${stop}"
}
