#!/usr/bin/env sh

# Usage: doc/api.md#require

require(){
	is_script=""
	is_cmd=""
	message="${2:-}"

    if [ -z "${1}" ]; then
        echo "require: arguments are missing"
        return 127
    fi

	if [ -n "$(command -v "${1}")" ]; then
		is_cmd=true
	elif [ -f "${1}" ]; then
		head -n1 "${1}" | grep -q '^#!'
		[ $? = 0 ] && is_script=true
	fi

	if [ -z "${is_cmd}" ] && [ -z "${is_script}" ]; then
		echo "Required resource not found: '${1}'"
		[ -n "${message}" ] && echo "${message}"
		
		return 127
	fi

	if [ -z "${is_cmd}" ]; then
		. "${1}"
		[ "${?}" != 0 ] exit "${?}"
	fi
}
