#!/usr/bin/env sh

shell_api_path="${SHELL_API_PATH:-'./shell'}"

# Enable strict mode
. "${shell_api_path}"/strict-mode

# Load dependencies
. "${shell_api_path}"/confirm
. "${shell_api_path}"/export-file
. "${shell_api_path}"/join-file
. "${shell_api_path}"/pipe-file
. "${shell_api_path}"/print-text
. "${shell_api_path}"/read-file
. "${shell_api_path}"/require
. "${shell_api_path}"/start-daemon
. "${shell_api_path}"/stop-daemon
. "${shell_api_path}"/substring
. "${shell_api_path}"/terminate
. "${shell_api_path}"/watch-daemon
. "${shell_api_path}"/write-file

# SHELL_API_PATH="$(pwd)/shell"; export SHELL_API_PATH; . shell/shell-api
