#!/usr/bin/env sh

# Usage: doc/api.md#start-daemon

# Create an alias
. ./shell/common/expand-aliases
alias start-daemon="start_daemon"

start_daemon(){
    mkdir -p /tmp/shell-api

    if [ -z "${1}" ]; then
        echo "start-daemon: arguments are missing"
        return 127
    else
        log_id="${1}"
        shift $(( $# > 0 ? 1 : 0 ))

        # Start as a background process
        # Write a log file and a process id file
        nohup "${*}" > "/tmp/shell-api/${log_id}.log" >/dev/null 2>&1 & \
        echo "${!}" > "/tmp/shell-api/${log_id}.pid"
    fi
}
