#!/usr/bin/env sh

# Usage: doc/api.md#stop-daemon

# Create an alias
. "${SHELL_API_PATH}"/common/expand-aliases
alias stop-daemon="stop_daemon"

stop_daemon(){
    pid_path="/tmp/shell-api/${1:-}.pid"

    if [ -z "${1}" ]; then
        echo "stop-daemon: arguments are missing"
        return 127
    elif [ ! -f "${pid_path}" ]; then
        echo "Cannot stop '${1}' - no such process"
        return 127
    else
        # Kill the process
        pid=$(cat "${pid_path}")
        kill -9 "${pid}" >/dev/null 2>&1

        # Cleanup the tmp files
        rm -rf "/tmp/shell-api/${1}.log"
        rm -rf "/tmp/shell-api/${1}.pid"
    fi
}
