#!/usr/bin/env sh

# Usage: doc/api.md#strict-mode

# Force POSIX-compliant behaviour
POSIXLY_CORRECT=1;
export POSIXLY_CORRECT

# --------------------------
# START Bash-specific rules
# --------------------------
shell_api_env=$(ps $$)

if [ -n "$(! set +B >/dev/null 2>&1)" ]; then
    # Disable brace expansion
    set +B
fi

if [ -z "${shell_api_env##*'/bin/bash'*}" ]; then
    # Prevent errors in a pipeline from being masked
    set -o pipefail

    # Expand aliases
    eval "shopt -s expand_aliases"
fi
# --------------------------
# END Bash-specific rules
# --------------------------

# '-e' instructs the shell to exit if a command has a non-zero exit status
# '-u' throws an error if an undefined variable is referenced
set -eu
