#!/usr/bin/env sh

# Usage: doc/api.md#strict-mode

# Force POSIX-compliant behaviour
POSIXLY_CORRECT=1;

# --------------------------
# START Bash-specific rules
# --------------------------
CURRENT_SHELL=$(ps -p $$ -oargs=)

if [ -n "$(! set +B >/dev/null 2>&1)" ]; then
    # Disable brace expansion
    set +B
fi

if test "${CURRENT_SHELL#*bash}" != "$CURRENT_SHELL"; then
    # Prevent errors in a pipeline from being masked
    set -o pipefail

    # Expand aliases
    eval "shopt -s expand_aliases"
fi
# --------------------------
# END Bash-specific rules
# --------------------------

# '-e' instructs the shell to exit if a command has a non-zero exit status
# '-u' throws an error if an undefined variable is referenced
set -eu
