#!/usr/bin/env sh

# Usage: doc/api.md#watch-daemon

# Create an alias
. ./shell/common/expand-aliases
alias watch-daemon="watch_daemon"

watch_daemon(){
    options=" -f"

    if [ -z "${1}" ]; then
        echo "watch-daemon: arguments are missing"
        return 127

    elif [ "${1}" = "-n" ] || [ "${1}" = "--no-follow" ]; then
        options=""
        shift $(( $# > 0 ? 1 : 0 ))
    fi

    log_path="/tmp/shell-api/${1}.log"

    if [ ! -f "${log_path}" ]; then
        echo "Cannot show output for '${1}' - no such process"
        return 127
    else
        tail"${options}" "${log_path}"
    fi
}
