#!/usr/bin/env sh

# Usage: doc/api.md#write-file

# Create an alias
. "${SHELL_API_PATH}"/common/expand-aliases
alias write-file="write_file"

write_file(){
    sudo_cmd=""

    if [ -z "${1}" ]; then
        echo "write-file: arguments are missing"
        return 127
    fi

    if [ "${1}" = "-a" ] || [ "${1}" = "--auth" ]; then
        sudo_cmd="sudo "
        shift $(( $# > 0 ? 1 : 0 ))
    fi

    if [ ! -f "${1}" ]; then
        directory=$(dirname "${1}")
        if [ ! -f "${directory}" ]; then mkdir -p "${directory}"; fi
        touch "${1}"
    fi

	echo "${2}" | "${sudo_cmd}"tee "${1}" >/dev/null 2>&1
}
