#!/usr/bin/env sh

. shell/terminate

ALLOW_EXTERNAL_SOURCE="${ALLOW_EXTERNAL_SOURCE:-}"

if [ "${1}" = "--yml" ]; then
    echo "Checking '.travis.yml'..."
    travis lint ./.travis.yml
fi

if [ "${1}" = "--sh" ]; then
    echo ""
    echo "Checking shell scripts..."

    SHELLCHECK_OPTS="\
    -e SC1071 \
    -e SC1090 \
    -e SC2016 \
    -e SC2034 \
    -e SC2116 \
    -e SC2119 \
    -e SC2148 \
    -e SC2181 \
    -e SC2185"

    RUN_SHELLCHECK="shellcheck ${ALLOW_EXTERNAL_SOURCE} ${SHELLCHECK_OPTS} {} +"
    eval "find ./test ./tool ./shell -type f -exec ${RUN_SHELLCHECK}"
fi

terminate "${?}" "PASS" "FAIL"
