#!/usr/bin/env sh

shells=bash,dash,fish,ksh,zsh

for current_shell in $(echo "${shells}" | sed "s/,/ /g"); do
    echo ""
    echo "--------------------------"
    echo "Testing in '${current_shell}' shell..."
    echo "--------------------------"


    if [ "${current_shell}" = 'dash' ]; then
        . ./test/shell-api.test
    else
        sed -i "s|env sh|env ${current_shell}|g" ./test/shell-api.test
        . ./test/shell-api.test
        sed -i "s|env ${current_shell}|env sh|g" ./test/shell-api.test
    fi
done
