#!/usr/bin/env sh

# Usage: doc/read/api.md#make_text
if [ "${1:-}" = 'make_text' ] || [ "${1:-}" = '--' ] || [ "${#}" -lt 1 ]; then
	make_text() {
		# Ensure $LC_ALL is set correctly or 'sed' will emit the following error:
		# sed: RE error: illegal byte sequence
		LC_ALL_CACHE="${LC_ALL:-}"
		LC_ALL='POSIX'
		export LC_ALL_CACHE
		export LC_ALL

		if [ "${#}" -lt 1 ]; then
			printf '%s\n' "Invalid input: Missing arguments"
			return 127
		elif [ "${#}" -gt 2 ]; then
			printf '%s\n' "Invalid input: Too many arguments"
			return 1
		fi

		limit=20
		class='print'

		is_integer() {
			case "${1#[+-]}" in
			*[!0-9]* | '') return 1 ;;
			esac || return 0
		}

		if is_integer "${1:-}"; then
			limit=${1:-}
			[ -n "${2:-}" ] && class=${2:-}
		elif is_integer "${2:-}"; then
			class=${1:-}
			limit=${2:-}
		elif [ -z "${2:-}" ] && [ -n "${1:-}" ]; then
			class="${1}"
		elif [ -n "${2:-}" ]; then
			printf '%s\n' "Invalid input: Not an integer"
			return 1
		fi

		# shellcheck disable=SC2016
		head -n "${limit}" /dev/urandom |
			sed "s/[.[\*^$()+?{|]/\\&/g" |
			sed "s/'/\\\'/g" |
			sed 's/"/\\"/g' |
			sed 's/`/\\`/g' |
			tr -cd "[:${class}:]" |
			head -c "${limit}"

		# Reset the value of $LC_ALL
		LC_ALL="${LC_ALL_CACHE}"
		export LC_ALL
	}
fi

if [ "${1:-}" = 'make_text' ] || [ "${1:-}" = '--' ] && [ "${#}" -gt 1 ]; then
	shift $(($# > 0 ? 1 : 0))
	eval "make_text ${*}"
	exit "${?}"
fi
