#!/usr/bin/env sh

# Internal helper function

# Expand aliases in BASH
current_shell=$(ps -p $$ -oargs=)

if test "${current_shell#*bash}" != "$current_shell"; then
    eval "shopt -s expand_aliases"
fi
