#!/usr/bin/env sh

# Internal helper function

# Expand aliases in BASH
shell_api_env=$(ps -p $$ -oargs=)

if test "${shell_api_env#*bash}" != "$shell_api_env"; then
    eval "shopt -s expand_aliases"
fi
